@startuml
top to bottom direction
:Utilisateur: -left- (Ouvrir page inscription)
:Utilisateur: -right- (Ouvrir page connexion)
:Utilisateur: -down- (Mot de passe oublié)
:Utilisateur: -up- (Se connecter)
:Serveur: -down- (Se connecter)
:Serveur: -right- (Envoie d'un mail de réinitialisation)
:Serveur: -left- (Inscription via formulaire)
(Inscription via formulaire) .> (Ouvrir page inscription) : include
(Envoie d'un mail de réinitialisation) .> (Mot de passe oublié) : include
(Se connecter) .> (Ouvrir page connexion) : include
(Ouvrir page connexion) .> (Mot de passe oublié) : extend
@enduml
