@startuml
|UTILISATEUR|
start
:Démarrage daemon;
|DAEMON|
:Authentification;
|BACKEND|
if (Verification d'identité) then (succès)
  |DAEMON|
  :Tracking;
  |UTILISATEUR|
  :Déclenche une action;
  |DAEMON|
  :Analyse;
  :Push;
  |BACKEND|
  :Analyse;
  :Persistance;
  end
else (échec)
  |BACKEND|
  end
endif
|UTILISATEUR|
:Arrêt daemon;
|DAEMON|
:Arrêt services;
stop
@enduml
