@startuml
left to right direction

actor Utilisateur

rectangle Daemon {

Utilisateur -- (Mise en pause/démarrage du tracking)
Utilisateur -- (Connexion au Daemon)
Utilisateur -- (Activer/désactiver filtres)

(Mise en pause/démarrage du tracking) .> (Connexion au Daemon) : <<include>>
(Activer/désactiver filtres) .> (Connexion au Daemon) : <<include>>
}
@enduml
