@startuml
left to right direction
skinparam packageStyle rectangle
actor Utilisateur
Utilisateur -- (Tracking)
Utilisateur -- (Paramètres)
Utilisateur -- (Nuisances)
(Tracking) .> (Authentification) : include
(Paramètres) .> (Authentification) : include
(Nuisances) .> (Authentification) : include
@enduml
