@startuml
|Client|

start
:Client (Daemon, web, ou mobile);
-> Requête HTTPS vers {domain}/account/create;

|#GhostWhite|Serveur d'authentification|
  :Vérifie validité de la requête;
  if (contient :\n- e-mail\n- mot de passe\n- nom de l'utilisateur) then (non)
    :Renvoie\nmessage d'erreur;

    |Client|
    :Affiche message d'erreur;
    end
  else (oui)

    |Base de données|
    if (Compte existe déjà ?) then (non)
      :Crée nouvel\nutilisateur en BDD;

      |Serveur d'authentification|
      :Envoie e-mail de confrmation;

      |Client|
      :Confirme création\nsous condition\nd'activation par email;
      stop

    |Base de données|
    else (oui)
      :Renvoie message d'erreur;

      |Client|
      :Affiche message d'erreur;
      end
    endif
  endif
@enduml
