@startuml
start

:Reçoit requête d'un client avec JWT;

if (JWT présent\n& valide ?) then (oui)
  :Continue l'opération;
  stop
else (non)
  :Envoi code d'erreur au client;
  end
endif


' JWT creation

start

:Reçoit requête d'un client avec identifiants;

if (Correct) then (oui)
  :Génère JWT;
  :Renvoi le JWT au client;
  stop
else (non)
  :Renvoi code d'erreur au client;
  end
@enduml
